<?php

namespace App\Services;

use App\Models\WirepickToken;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use phpseclib3\Crypt\PublicKeyLoader;
use phpseclib3\Crypt\RSA;

class WirepickService
{
    private $publicKey;
    private $apiKey;

    public function __construct()
    {
        $this->publicKey = config('wirepick.public_key');
        $this->apiKey    = config('wirepick.api_key');
    }

    /**
     * Encrypt Card Info
     */
    public function encryptCard(array $cardInfo)
    {
        $jsonCard = json_encode($cardInfo, JSON_UNESCAPED_SLASHES);

        $key = PublicKeyLoader::load($this->publicKey)
            ->withPadding(RSA::ENCRYPTION_OAEP)
            ->withHash('sha256')
            ->withMGFHash('sha256');

        return base64_encode($key->encrypt($jsonCard));
    }

    /**
     * Get token generated by BACKGROUND JOB ONLY
     */
    public function getAccessToken()
    {
        $token = WirepickToken::latest()->first();

        if (!$token) {
            throw new \Exception("WIREPICK ERROR: No token available.");
        }

        if (now()->greaterThan($token->expires_at)) {
            throw new \Exception("WIREPICK ERROR: Token expired. Background refresh pending.");
        }

        return $token->access_token;
    }

    /**
     * Refresh token (USED ONLY BY QUEUE JOB)
     */
    public function refreshAccessToken()
    {
        Log::info("WIREPICK: Refreshing token (background job)...");

        $response = Http::asForm()
            ->withHeaders([
                "x-api-key" => config("wirepick.api_key"),
            ])
            ->post("https://apigw.thehotpatch.com/oauth2/token", [
                "grant_type"    => "client_credentials",
                "client_id"     => config("wirepick.client_id"),
                "client_secret" => config("wirepick.client_secret"),
            ]);

        if (!$response->successful()) {
            Log::error("WIREPICK TOKEN ERROR", [
                "status" => $response->status(),
                "body"   => $response->body(),
            ]);

            throw new \Exception("Cannot refresh Wirepick token");
        }

        $json = $response->json();

        WirepickToken::create([
            "access_token" => $json["access_token"],
            "expires_in"   => $json["expires_in"],
            "expires_at"   => now()->addSeconds($json["expires_in"]),
        ]);

        Log::info("WIREPICK: Token refreshed successfully.");
    }

    public function getReport(array $payload)
{
    $token = $this->getAccessToken();

    // Build correct request body
    $requestBody = [
        "start_date"    => $payload["start_date"],
        "end_date"      => $payload["end_date"],
        "report_format" => $payload["report_format"] ?? "JSON",
        "action"        => "general_report",
        "environment"   => "PROD",
    ];

    Log::info("WIREPICK REPORT REQUEST", $requestBody);

    // Endpoint — always Airtel's reports URL
    $endpoint = "https://apigw.thehotpatch.com/prod/v1/airtelmoneyopenapi/reports";
        $endpoint = "https://apigw.thehotpatch.com/prod/v1/sbiczmecommapi/reports";

    $response = Http::withToken($token)
        ->withHeaders([
            "x-api-key"    => config("wirepick.api_key"),
            "Content-Type" => "application/json",
        ])
        ->post($endpoint, $requestBody);

    Log::info("WIREPICK REPORT RESPONSE", [
        "status" => $response->status(),
        "body"   => $response->json(),
    ]);

    return $response->json();
}

    /**
     * Payment Request - Uses ONLY valid token
     */
    public function pay(array $payload, string $type = 'card')
    {
        $token = $this->getAccessToken(); // NEVER refresh during payment

        $url = match ($type) {
            'card'   => 'https://apigw.thehotpatch.com/uat/sbiczmecommapi/request',
            //    'card'   => 'https://apigw.thehotpatch.com/uat/sbiczmecommapi/request',
            'airtel' => 'https://apigw.thehotpatch.com/uat/airtelmoneyopenapi/request',
            'mtn'    => 'https://apigw.thehotpatch.com/uat/mtnopenapi/request',
            default  => throw new \Exception("Unknown gateway type")
        };

        try {
            $response = Http::timeout(15)->withHeaders([
                "Authorization" => "Bearer {$token}",
                "x-api-key"     => $this->apiKey,
                "Content-Type"  => "application/json",
            ])->post($url, $payload);

            $json = $response->json();

        } catch (\Throwable $e) {
            Log::error("WIREPICK TIMEOUT", ["error" => $e->getMessage()]);

            return [
                "error"   => true,
                "type"    => "timeout",
                "message" => "Wirepick request timed out."
            ];
        }

        // Token expired in middle of payment (rare)
        if (isset($json["message"]) && str_contains($json["message"], "token has expired")) {

            Log::error("WIREPICK TOKEN EXPIRED DURING PAYMENT");

            return [
                "error"   => true,
                "status"  => "token_expired",
                "message" => "Wirepick token expired. Please retry.",
            ];
        }

        return $json;
    }
}
