<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Rent Receipt • {{ $month instanceof \Carbon\Carbon ? $month->format('Y-m') : $month }}</title>

  <style>
    @page { margin: 28px; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color:#111; line-height: 1.5; }
    .wrap { max-width: 720px; margin: 0 auto; }
    h1 { font-size: 22px; margin: 0 0 4px; }
    .muted { color:#6b7280; }
    .box { border:1px solid #e5e7eb; border-radius:12px; padding:14px; margin-bottom:14px; }
    .row { display:flex; justify-content:space-between; gap:12px; }
    .label { font-weight:700; font-size:11px; color:#6b7280; text-transform:uppercase; }
    .value { font-weight:700; margin-bottom:6px; }
    table { width:100%; border-collapse:collapse; margin-top:10px; }
    th, td { padding:8px; border-bottom:1px solid #e5e7eb; text-align:left; vertical-align:top; }
    th { background:#f9fafb; font-size:11px; text-transform:uppercase; color:#6b7280; }
    .total { font-size:14px; font-weight:900; }
    .footer { margin-top:20px; font-size:11px; color:#6b7280; text-align:center; }
    .pill {
      display:inline-block; padding:6px 10px; border-radius:999px; font-weight:800; font-size:11px;
      border:1px solid #e5e7eb; background:#f9fafb; color:#111;
    }
  </style>
</head>
<body>

<div class="wrap">

  {{-- HEADER --}}
  <div class="row" style="align-items:flex-start;">
    <div>
      <h1>Rent Receipt</h1>
      <div class="muted">
        Month:
        <strong>
          {{ ($month instanceof \Carbon\Carbon ? $month : \Carbon\Carbon::parse($month.'-01'))->format('F Y') }}
        </strong><br>
        Generated: {{ now()->format('d M Y H:i') }}
      </div>
    </div>

    <div style="text-align:right;">
      <div class="pill">{{ $property->property_name }}</div>
    </div>
  </div>

  <hr style="margin:14px 0;">

  {{-- TENANT + UNIT --}}
  <div class="box">
    <div class="row">
      <div>
        <div class="label">Tenant</div>
        <div class="value">{{ $tenant->name ?? $lease->tenant->name }}</div>
        <div class="muted">{{ $tenant->email ?? $lease->tenant->email }}</div>
      </div>

      <div style="text-align:right;">
        <div class="label">Unit</div>
        <div class="value">{{ optional($unit)->code ?? optional($lease->unit)->code ?? '—' }}</div>
        <div class="muted">{{ $property->address ?? '—' }}</div>
      </div>
    </div>
  </div>

  {{-- SUMMARY --}}
  <div class="box">
    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th style="width:160px;">Amount (K)</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>Monthly Rent</td>
          <td>{{ number_format($monthlyRent, 2) }}</td>
        </tr>
        <tr>
          <td>Total Paid</td>
          <td>{{ number_format($paidTotal, 2) }}</td>
        </tr>
        <tr>
          <td><strong>Balance</strong></td>
          <td class="total">{{ number_format($balance, 2) }}</td>
        </tr>
      </tbody>
    </table>
  </div>

  {{-- PAYMENT LINES --}}
  <div class="box">
    <div class="label">Payment Breakdown</div>

    <table>
      <thead>
        <tr>
          <th>Date</th>
          <th>Method</th>
          <th>Reference</th>
          <th style="width:140px;">Amount (K)</th>
        </tr>
      </thead>
      <tbody>
        @foreach($payments as $p)
          <tr>
            <td>{{ \Carbon\Carbon::parse($p->payment_date)->format('d M Y') }}</td>
            <td>{{ ucfirst(str_replace('_',' ', $p->method ?? 'cash')) }}</td>
            <td>{{ $p->reference ?? '—' }}</td>
            <td>{{ number_format($p->amount, 2) }}</td>
          </tr>
        @endforeach
      </tbody>
    </table>
  </div>

  <div class="footer">
    Generated by {{ config('app.name') }} • System receipt (valid without signature)
  </div>

</div>

</body>
</html>
